name: Deploy to Firebase hosting

on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # You can choose the Node version you want

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React app for production
      - name: Build the React app
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: coffeebrewrecipe
          channelId: live
